language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull ehhnwidex/accurev:latest
  - docker ps -a
  - echo -e "machine github.com\n  login $api_key" > ~/.netrc
script:
  - mvn -e -Dmaven.test.skip=false -Dsurefire.useFile=false clean test package --settings ./settings.xml
  - mvn surefire-report:report-only
  - cat target/surefire-reports/*.txt
deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true