services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull ehhnwidex/accurev:latest
  - docker ps -a
script:
  - docker-compose -f docker-compose-build.yml up --build
deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true