language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - curl -fsSL http://cdn.microfocus.com/cached/legacymf/Products/accurev/accurev7.3/accurev-7.3-linux-x86-x64-clientonly.bin -o ./accurev-client.bin
  - chmod +x ./accurev-client.bin
  - sudo ./accurev-client.bin -i silent -f ./installer.properties
  - export PATH=$PATH:/var/AccurevClient/bin/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull ehhnwidex/accurev:latest
  - docker ps -a
script:
  - mvn -e -Dmaven.test.skip=false -Dsurefire.useFile=false clean test package
  - mvn surefire-report:report-only
  - cat target/surefire-reports/*.txt
deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true