language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull ehhnwidex/accurev:latest
  - docker ps -a
script:
  - mvn clean package
after_failure:
  - cat target/surefire-reports/*.txt
  - mvn surefire-report:report-only
deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true