sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker pull ehhnwidex/accurev:latest
#  - docker ps -a
before_script:
  - ./install.sh
  - export PATH=$PATH:/var/AccurevClient/bin/
script:
  - mvn -e -Dmaven.test.skip=false -Dsurefire.useFile=false clean test package
  - mvn surefire-report:report-only
  - cat target/surefire-reports/*.txt
deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true