language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull widexehhn/accurev:latest
  - docker ps -a
script:
  - mvn clean package

deploy:
  provider: releases
  api_key: $api_key
  file:
    - target/accurev-scm.hpi
    - target/accurev-scm.jar
  skip_cleanup: true
  draft: true