language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull wimill/accurev:latest
  - docker ps -a
script:
  - mvn clean package

deploy:
  provider: releases
  api_key: $api_key
  file:
    - build/libs/accurev-client.hpi
    - build/libs/accurev-client-plugin-1.0.0-SNAPSHOT-all.jar
  skip_cleanup: true
  draft: true